kind: pipeline
type: docker
name: node12

steps:
- name: build
  image: node:12-alpine
  commands:
  - npm --version
  - npm install -g npm
  - npm --version
  - npm install
  - npm run build

---
kind: pipeline
type: docker
name: node14

steps:
- name: build
  image: node:14-alpine
  commands:
  - npm --version
  - npm install -g npm
  - npm --version
  - npm install
  - npm run build

---
kind: pipeline
type: docker
name: node15

steps:
- name: build
  image: node:15-alpine
  commands:
  - npm --version
  - npm install -g npm
  - npm --version
  - npm install
  - npm run build
